AsiaLabv1/Controllers/MainController.cs
using AsiaLabv1.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AsiaLabv1.Controllers
{
    public class MainController : Controller
    {

        //this class is used for user/employee related queries
        //any query related to employee has been written in this class
        UserService UsersService = new UserService();
        BranchService BranchesService = new BranchService();

        public ActionResult LoginPage()
        {
            return View("LoginPage");
        }

        public ActionResult Khaali()
        {
            return View();
        }

        public ActionResult EditProfile()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(FormCollection LoginForm)
        {

            /*
             * for admin login and password
                username: testadmin
                password: admin2016
             * for reciptionist login and password
                username:  TestReceiptionist
                password:  TestReceiptionist2016
             */


            #region commented bekar code baad m delete krdengy ye
            //UsersService.AddUserType("Admin");
            //UsersService.AddUserType("Doctor");
            //UsersService.AddUserType("Receptionist");
            //UsersService.AddUserType("Technician");

            //BranchesService.AddBranch("branch1name", "branch 1 address", "Br Code");

            //UsersService.AddUser();
         //   var t = UsersService.GetAllUserTypes();
          //  var a = BranchesService.GetAllBranches();

           // UsersService.AddUser();
            //var t = UsersService.GetAllUserTypes();
            // var a = BranchesService.GetAllBranches();
            #endregion

            string username = LoginForm["Email"].ToString();
            string password = LoginForm["Password"].ToString();

            var model = UsersService.ValidateLogin(username, password);

            if (model != null)
            {
                Session["loginuser"] = model.Id;
                Session["loginusername"] = model.Name;

                if (model.Name == "Humam admin")
                {
                    Session["AdminLabelShow"] = model.Name;
                }
                
                Session["branch"] = model.BranchName;
                return View(model.UserRole + "Dashboard", model);
            }

            return RedirectToAction("LoginPage");
        }

        public ActionResult abc()
        {
            return View();
        }


        public ActionResult LogOut()
        {
            Session["loginuser"] = null;
            Session["loginusername"] = null;
            Session["AdminLabelShow"] = null;
            return RedirectToAction("LoginPage");
        }

    }
}

AsiaLabv1/Controllers/TechnicianController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AsiaLabv1.Controllers
{
    public class TechnicianController : Controller
    {

        public ActionResult Index()
        {
            
            return View();
        }

        public ActionResult PerformTest()
        {

            return View();
        }
        

    }
}

AsiaLabv1/Views/Technician/PerformTest.cshtml
@{
    ViewBag.Title = "PerformTest";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@section Banner
{
    <div class="banner">

        <h2>
            <a href="index.html">Home</a>
            <i class="fa fa-angle-right"></i>
            <span>Perform Test</span>
        </h2>
    </div>
}

@*---------Start Side Navigation Menu-----------*@

@section NavMenu
{
    <li>
        <a href="@Url.Action("TechnicianDashboard", "Main")" class=" hvr-bounce-to-right"><i class="fa fa-dashboard nav_icon "></i><span class="nav-label">Dashboard</span> </a>
    </li>

    <li><a href="@Url.Action("PerformTest", "Technician")" class=" hvr-bounce-to-right"><i class="fa fa-desktop nav_icon"></i>Perform Test</a></li>





}
@*------------ End Side Navigation Menu----------*@


@*------------- Start Main Content Code-------------*@

<div class="grid-form">

    <!----->
    <!---->
    <div class="grid-form1">

        <div class="tab-content">

            <div class="tab-pane active" id="horizontal-form">

                <div class="horz-grid">
                    <div class="grid-hor">
                        <h4 id="grid-example-mixed-complete">Perform Test</h4><br />
                        <h5 id="grid-example-mixed-complete">Patient No. 1008</h5>
                        <h5 id="grid-example-mixed-complete">Patient Name: Akhtar</h5>

                    </div>
                    <!---->

                    <div class="row show-grid">
                        <div class="col-xs-6 col-sm-3">Test Name</div>
                        <div class="col-md-1">Result</div>

                        <div class="col-xs-6 col-sm-3">Lower Bound</div>
                        <div class="col-xs-6 col-sm-3">Upper Bound</div>
                        <div class="col-md-1">Unit</div>


                    </div>
                    <div style="border: 2px; border-style: solid;  color: #d95459; ">

                    </div>

                    <div class="row show-grid">
                        <div class="col-xs-6 col-sm-3">
                            Urine
                            <br />
                        </div>
                        <div class="col-md-1"><input type="text" class="form-control" id="focusedinput" placeholder="Result"></div>
                        <div class="col-xs-6 col-sm-3">20</div>
                        <div class="col-xs-6 col-sm-3">50</div>
                        <div class="col-md-1">mg%</div>


                    </div>
                    <div class="row show-grid">
                        <div class="col-xs-6 col-sm-3">Blood Sugar</div>
                        <div class="col-md-1"><input type="text" class="form-control" id="focusedinput" placeholder="Result"></div>
                        <div class="col-xs-6 col-sm-3">120</div>
                        <div class="col-xs-6 col-sm-3">250</div>
                        <div class="col-md-1">mg%</div>


                    </div>


                </div>


                <div class="col-sm-2 login-do" style="margin-left:40%">
                    <label class="hvr-shutter-in-horizontal login-sub">
                        <input type="submit" value="Submit" onclick="window.location='signup.html';" />
                    </label>
                </div>


                <div class="clearfix"> </div>
                
            </div>
        </div>
    </div>
</div>
<br /><br /><br />

<!--//grid-->
@*------------- End Main Content Code-------------*@